//! Septima — GTK4 / libadwaita frontend for 7-Zip ZS (`7zz`).

mod archive_view;
mod create_dialog;
mod entry_object;
mod hash_dialog;
mod preset;
mod progress_row;
mod window;

mod config {
    // Generated by build.rs (see config.rs.in). Some constants (e.g. VERSION)
    // are consumed by later tasks (About dialog); allow them ahead of use.
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/config.rs"));
}

use adw::prelude::*;
use gtk::{gio, glib};

use crate::window::SeptimaWindow;

fn main() -> glib::ExitCode {
    // i18n plumbing from commit one (Kickoff A1). No catalogs exist yet; this
    // just registers the text domain so the Blueprint `_()` strings translate
    // once po/ lands — retrofitting later is miserable.
    gettextrs::setlocale(gettextrs::LocaleCategory::LcAll, "");
    gettextrs::bindtextdomain(config::GETTEXT_PACKAGE, config::LOCALEDIR)
        .expect("bindtextdomain");
    gettextrs::bind_textdomain_codeset(config::GETTEXT_PACKAGE, "UTF-8")
        .expect("bind_textdomain_codeset");
    gettextrs::textdomain(config::GETTEXT_PACKAGE).expect("textdomain");

    // Load the compiled gresource bundle (window.ui, style.css) from the install
    // dir under Meson, or OUT_DIR under a plain `cargo` build (see build.rs).
    let gresource_path = format!("{}/septima.gresource", config::PKGDATADIR);
    let resource = gio::Resource::load(&gresource_path)
        .unwrap_or_else(|e| panic!("failed to load gresource at {gresource_path}: {e}"));
    gio::resources_register(&resource);

    let app = adw::Application::builder()
        .application_id(config::APP_ID)
        .flags(gio::ApplicationFlags::HANDLES_OPEN)
        .build();

    app.connect_startup(|_| load_css());
    app.connect_activate(|app| present(&window_for(app)));
    app.connect_open(|app, files, _hint| {
        let window = window_for(app);
        if let Some(file) = files.first() {
            window.open_file(file.clone());
        }
        present(&window);
    });

    app.run()
}

fn window_for(app: &adw::Application) -> SeptimaWindow {
    app.active_window()
        .and_downcast::<SeptimaWindow>()
        .unwrap_or_else(|| SeptimaWindow::new(app))
}

fn present(window: &SeptimaWindow) {
    // Fully qualified: adw::prelude globs several traits that each define
    // `present()`, so a bare method call is ambiguous.
    gtk::prelude::GtkWindowExt::present(window);
}

fn load_css() {
    let provider = gtk::CssProvider::new();
    provider.load_from_resource(&format!("{}/style.css", config::GRESOURCE_PREFIX));
    if let Some(display) = gtk::gdk::Display::default() {
        gtk::style_context_add_provider_for_display(
            &display,
            &provider,
            gtk::STYLE_PROVIDER_PRIORITY_APPLICATION,
        );
    }
}
